// ≈ 200 prénoms courants en France, origines variées, sans accents (A–Z uniquement, forme canonique).
export const NAMES = `
LEA EMMA JADE LOUISE ALICE CHLOE LINA MILA ROSE ANNA AMBRE JULIA MIA LENA ZOE INES
LOU AGATHE JULIETTE IRIS NINA EVA CAMILLE SARAH MANON CLARA LOLA ROMANE CHARLOTTE ELISE
LUCIE ADELE CELIA OCEANE NOEMIE MARGOT MAELYS LISE JEANNE VICTOIRE CAPUCINE CLEMENCE
ELENA SOFIA YASMINE AYA SALOME HANAE NOUR MARIAM FATOU AMINATA AICHA LEILA SAMIRA
MAISSA NAEL KENZA SHAINA ESTHER RACHEL MYRIAM HELENE MARIE ANNE SOPHIE NATHALIE ISABELLE
SYLVIE CATHERINE MONIQUE FRANCOISE CHANTAL MARTINE CELINE AURELIE LAURA JULIE EMILIE PAULINE
MATHILDE ELOISE GABRIELLE MARGAUX LOUNA LUNA ELLA ALBA THAIS LIV MAYA KIARA LINH MEI
GABRIEL LEO RAPHAEL LOUIS ARTHUR JULES ADAM MAEL LUCAS HUGO NOAH SACHA PAUL NATHAN
GABIN AARON TOM THEO MARTIN NOLAN ETHAN ELIOTT MATHIS TIMEO VICTOR AXEL ANTOINE EDEN
SAMUEL LIAM MAXIME ROBIN AUGUSTIN NAIM ISSA YANIS MOHAMED IBRAHIM ILYES AYOUB RAYAN
WASSIM ADEM AMIR YOUSSEF MALIK SOFIANE KARIM MEHDI BILAL OMAR IDRISS MAMADOU MOUSSA
SEKOU DIEGO MATEO ENZO LORENZO MARCO PABLO HUGUES BASTIEN CLEMENT THOMAS ALEXANDRE NICOLAS
JULIEN PIERRE JEAN MICHEL PHILIPPE ALAIN BERNARD PATRICK DANIEL ERIC FREDERIC LAURENT
OLIVIER VINCENT SEBASTIEN DAVID BENJAMIN SIMON ELIAS ISAAC NOE AMAURY BAPTISTE QUENTIN
VALENTIN CORENTIN TRISTAN ROMAIN FLORIAN DORIAN KYLIAN MILO MARIUS LENNY EVAN NILS SVEN
OSCAR FELIX ACHILLE OWEN IVAN IGOR ANTON LUKA STEFAN KENJI HIRO MINH TRAN CHEN WEI
ARJUN RAVI ANIL DEV KOFI KWAME YAO JOAO TIAGO RAFAEL CARLOS
`.trim().split(/\s+/);
